server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service #应用名称
mybatis:
  type-aliases-package: com.advance.entity
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
      register-with-erueka: true  # 服务注册：服务提供者启动时，会检测该属性，若为true，则想EurekaServer发起一个rest请求，携带自己的元数据，
                                  # EurekaServer把信息保存到一个双层Map中，第一层Map的key就是服务的名称，第二层的Map的key就是服务的实例ID
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-renewal-interval-in-seconds: 30 # 服务续约的间隔，默认30秒（30心跳，基于客户端）
    lease-expiration-duration-in-seconds: 90 # 服务失效时间，默认值90秒（90过期，基于Eureka）
        #   默认情况下每30秒，服务向注册中心发送一次心跳，证明自己还在运行，若超过90秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除
        #

