server:
  port: 8762 #默认端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    #  instance:
    #     启动的实例ID：${hostname} + ${spring.application.name} + ${server.port} 默认（实例的唯一标准）
    #    instance-id: ${spring.application.name}:${server.port}
  server:
#     Eureka失效剔除，内存溢出，网络故障等原因导致服务无法正常工作，需要开启定时任务，默认60秒对（超过90秒未响应）失效服务进行剔除
    eviction-interval-timer-in-ms: 60000
#     关闭Eureka的自我保护机制，由于心跳有某种原因连接不上，Eureka统计最近15分钟心跳失败的服务失败比例是否超过85%,
#     此时剔除肯定不妥当，因为服务可能没有宕机，Eureka会把当前实例的注册信息保护起来，不予剔除。
    enable-self-preservation: true